### ISSUE TITLE
Missing Data Files for Hopper and Swimmer Tasks

### ISSUE THREAD

**Issue by yassineCh** [lamda-bbo/offline-moo#2]
When running the `mo_hopper_v2`  task in tests/test_env, I encountered the following error:
data/mo_hopper_v2/params_shapes.pkl not found. Similarly for swimmer.

The folder contains the following files only:
mo_hopper_v2-test-x-0.npy
mo_hopper_v2-test-y-0.npy
mo_hopper_v2-x-0.npy
mo_hopper_v2-y-0.npy

It appears `params_shapes.pkl` is missing. Could you provide this file or update the data google drive? I appreciate your help.

**Comment by trxcc** [comment]
Hi @yassineCh 

Thanks for your issue!

This is indeed our oversight. We have updated ``params_shape.pkl`` in our Google Drive. 

If you have any questions, feel free to contact us.

**Comment by yassineCh** [comment]
Thank you for the update. I appreciate your prompt response.
